### ISSUE TITLE
[Feature]: CPU Limiter needed - High CPU Usage

### ISSUE THREAD

**Issue by sweah** [sagetarian/skype-wrapper#19] opened 2011-11-16 08:55 UTC
Hi!

After starting skype-wrapper, everything works as expected (except the count for missed messages in launcher), but skype has a constant cpu load of ~40% and indicator-skype ~12%. 

I run Ubuntu 11.10 64bit.

**Comment by sweah** [comment] 2011-11-16 09:06
Hi

If I kill indicator-skype and run /usr/share/skype-wrapper/indicator-applet-skype.py in a terminal, there's the following message at the beginning:

/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject

**Comment by sagetarian** [comment] 2011-11-16 09:32
that import assertion is negligent :) thanks .. but you've noted 2 key bugs:
1. Unoptimal CPU usage
2. Count for missed messages is failing on your system for some reason

If you go into dconf-editor and enable debug-log .. can you send me a link to your log output .. the log file can be found in

~/.skype-wrapper/log.txt

**Comment by sweah** [comment] 2011-11-16 09:55
you can find my log.txt here: http://ubuntuone.com/3ULW4LUas4IKI2GWWbtQbf

**Comment by sagetarian** [comment] 2011-11-16 10:37
Thanks .. you're a legend .. but i'll prob have to add alot more debugging to nail it down .. sorry .. will have something by tonight ..

**Comment by bilderbuchi** [comment] 2011-11-16 20:06
I can reproduce the high CPU usage.

**Comment by sagetarian** [comment] 2011-11-17 08:57
Can you test if the new "unstable" version in the repo fixes this (EXPERIMENTAL) .. I've add a cpu limiter in the code that will make the application bar its performance .. at the moment i need to rework where i limit the CPU usage as it sometimes waits in between events now , so you'll see the UMM update before the launcher etc etc .. will fix this .. but let me know if this lowers the CPU usage and doesn't make the notifications take toooooo long to show .. 

in your dconf-editor there is now an option for "CPU-Limit" where you specificy how much percentage of the CPU time it can use .. atm its a 7.5% , which sounds high, but it drops between 3% and 9% over here and knocks skypes usage all the way down to 0% to 10% over here

https://github.com/downloads/sagetarian/skype-wrapper/skype-wrapper_0ubuntu5-3.3_all.deb

**Comment by sweah** [comment] 2011-11-17 10:03
with the new version and a CPU-Limit of 7,5% the load is a little lower, but still 31-40% skype and 6-7% indicator-skype.
I'll test some different values of CPU-Limit later.

thank you for your efforts!!!!

**Comment by sagetarian** [comment] 2011-11-17 10:32
pleasure :) try a setting of 5% .. i see average "gwibber" like performance, meaning that its performing alot more like a "background" process

**Comment by sweah** [comment] 2011-11-17 10:52
with 4% I have 15-20% skype and 4% indicator-skype. 

Do you have a clue, why I have this high load and others don't?

**Comment by sagetarian** [comment] 2011-11-17 11:22
nah, its not just you .. the only reason why im not affected is cause i have a triple core .. but it would be a sucky applet if it took too much resources .. can you check how much CPU skype uses without this?

**Comment by bilderbuchi** [comment] 2011-11-17 11:28
I'm also affected. Normally when skype runs it takes negligible performance, (0-1%? I'll get you numbers in the evening if needed). I suspect something skype-wrapper does for the notifications makes both eat cpu. I think (can confirm in the evening) that when notifications don't work (because of the custom command I use), skype's cpu usage is normal.

**Comment by sagetarian** [comment] 2011-11-17 11:43
I concurr

try this version. It is a more stable use of the limiter and it has increased gtk_timeout periods .. on my system it knocks skype down to 0% majority of the time and 3% max .. same with indicator-skype.. i would like your stats :)

https://github.com/downloads/sagetarian/skype-wrapper/skype-wrapper_0ubuntu5-3.5_all.deb

**Comment by sweah** [comment] 2011-11-17 14:07
with 4% CPU-Limit I have 8-15% skype and 2-4% indicator-skype. Much better than yesterday!!
Normally skype has 1% load

My launcher is not reacting at all. no count for unread messages, no transfer progress, ...

**Comment by sagetarian** [comment] 2011-11-17 14:29
not cool .. okay, im developing the skypeproxy class and we'll see how that goes .. then i'll fix up the cpu limiter to not effect notifications

watch this space

**Comment by sweah** [comment] 2011-11-17 14:52
I'm not sure if the limiter causes the problem with launcher count. maybe it also didn't work with earlier versions...

But the load is okay now and I'm looking forward to further improvements.

you do a great job!!!!!!

**Comment by sagetarian** [comment] 2011-11-17 15:23
I believe we may not need a skypeproxy anymore and i believe i managed to sort out the issue at all .. try this one and let me know about 
1. Does your launcher update
2. CPU of indicator-skype

https://github.com/downloads/sagetarian/skype-wrapper/skype-wrapper_0ubuntu5-3.6_all.deb

**Comment by sweah** [comment] 2011-11-17 15:51
this version does not run for me. I get the following error:

Traceback (most recent call last):
  File "indicator-applet-skype.py", line 35, in <module>
    import skypeproxy
ImportError: No module named skypeproxy
Applet closed
API crash detected
Restarting skype-wrapper

**Comment by sagetarian** [comment] 2011-11-17 16:02
Sorry mate .. i reuploaded it .. try again .. my bad :P #facepalm

**Comment by sweah** [comment] 2011-11-17 17:32
No problem, but still the same error message here...

Traceback (most recent call last):
  File "indicator-applet-skype.py", line 35, in <module>
    import skypeproxy
ImportError: No module named skypeproxy
Applet closed
API crash detected
Restarting skype-wrapper

**Comment by sagetarian** [comment] 2011-11-17 19:54
#facepalm x2 

just to be sure i've upload it on a new version number

https://github.com/downloads/sagetarian/skype-wrapper/skype-wrapper_0ubuntu5-3.7_all.deb

**Comment by sweah** [comment] 2011-11-18 08:52
great performance :) now, i've got for both, skype and indicator-skype, a load of 1%maximum!!

and launcher count is also working for me now! 
I still get many user-online-messages at startup although I've unchecked notify-on-initializing, but that's no problem for me! I'm very happy with skype-wrapper!!!

once again: great job!!

**Comment by sagetarian** [comment] 2011-11-18 08:57
Awesome .. im closing this .. will open a bug for that notify-on-initializing

**Closed as completed by sagetarian** 2011-11-18 08:57 UTC
Labels: Bugs, Features
