### ISSUE TITLE
Can't get it working on Ubuntu 12.04.1 + Skype 4.0

### ISSUE THREAD

**Issue by Vincent123** [sagetarian/skype-wrapper#68] opened 2012-08-28 09:59 UTC
As I get it, the wrapper gets integrated into the default message-indicator,  so I'd see that blue envelope on unread messages, pop-ups on new ones and so on.
But the thing is that it simply doesn't work. Well, I see it in the messages-indicator, but:
1) No pop-ups on new messages
2) No status sync (if I choose 'offline', it changes in pidgin but not in skype)
3) No 'blue envelope'
What works:
1) Wrapper-settings application
2) Tons of notifications about contacts online when the app starts
3) When running from terminal, the program sees people coming on- or off-line.
Tried skypes both from the official ubuntu repository and the official skype site - none worked.
Running fresh install of Ubuntu 12.04.1 LTS 64-bit.
Suspicions:
1) Maybe the package depends on some official software?
I purged totem, empathy, gwibber and some other stuff I don't need. Pidgin does work, though.
2) Skype 4.0.0.8 isn't supported?
http://pastebin.com/RzrxCda7
And yes, http://www.webupd8.org/2011/05/skype-ubuntu-messaging-menu-notifyosd.html
this thing works, but it has poor support of 'group' chats (conferences), so I gave up.
P.S. One or two times I saw it work, but only half-way. I clicked the message-indicator icon and saw some people write me (under 'skype' icon I had their names), but that was on the skype from the official ubuntu repository.

**Comment by grissir** [comment] 2012-08-28 12:03
Hi
First of all Skype 4.0 is supported although not tested completely
The status change bug is definitely caused by the removal of empathy. 

The pop-ups have settings but should be enabled by default.
If you want to help use dconf- editor to set a higher log level. But I will look into it at the end of the week

**Comment by stonerl** [comment] 2012-08-28 12:08
Hi,

Skype 4.0.0.8 is supported and it is working here on my system, (exactly the same setup only 32 & 64bit with Skype from USC, maybe you should use this version over of the vanilla packages from Skype)

1) Since you uninstalled empathy i guess you also uninstalled the "telepathy-mission-control-5"-package which is necessary for skype-wrapper to sync with your global onlinestatus.

Could you run skype-wrapper from shell for a while and past the output? Especially I'm  interested about the notifications for offline/online users ? 

The ouptut you pasted says that the API request timed out, as far as I can tell. How many people are in you contact list?

You said that you sometimes get notifications(blue envelope), with the chat partners name. So it tells me that it is working sometimes.

**Comment by Vincent123** [comment] 2012-08-28 12:43
First of all, thanks for the answers! Even didn't expect that :P
Re-installed empathy and gwibber, telepathy was still there as I see.
Ran skype from the wrapper and noticed that it now reacts on status changes, so you were right about empathy.
Now I was trying to get that blue envelope working, and for now the combo is:
1) Run skype from the wrapper (pinned to the unity launcher)
2) Open the 'real' skype through indicator-messages, open the chat window with somebody and minimise it
3) Ask him/her to write you smth and you'll get the blue envelope!
I'll try some other combos but can't wait to post my current progress.
By the way, when I open skype even using indicator-messages, it has the separate icon (not like wrapper has) in the unity launcher.
http://askubuntu.com/a/142894 and also some people suggested change both Skype icons' command paths to skype-wrapper, I'll check that out.

**Comment by grissir** [comment] 2012-08-28 13:19
We have a bug report for the two icons, the problem is I can't reproduce it
By the way focused chats will never have notifications

**Comment by Vincent123** [comment] 2012-08-28 14:36
I'm going to simply add the wrapper to the autorun, not pinning it.
I have to admit that empathy has to be configured, if not - the status thing doesn't work. At least the status thing, maybe the whole plugin, I didn't check.
http://pastebin.com/Uqj9n2ch
in one of the strings, X is the user nickname - there are several messages like that for different users.
The terminal keeps getting strings 71-72 at least once a second (don't know the actual period).
Sometimes there are also messages like "User X is online" between them.
But the main problem for me is that the envelope works only and only when I already have the conversation window open, but minimised. Closed window = neither envelop, not libnotify pop-ups.
Also, when I got a standard skype pop-up about a new message in a conference and opened its window, in terminal I got

INFO: Checking unread messages
WARNING: Checking unread messages failed: local variable 'display_name' referenced before assignment

Kept the conference window open and minimised, but for this case notifications didn't work as if it was closed, except for a repeating string with the warning on new messages in it.

**Comment by stonerl** [comment] 2012-08-28 15:23
Ok i think I know where the error could come from. With my last Pull Request I changed the way skype-wrapper handles the Usernames for notifications. 

Does the user who writes you messages have a Fullname. You can check this if you right click on the user and select Profile. If he doesn't than this could be the bug I already fixed this in my branch.

What happens is that skype-wrapper tries to assign  the Fullname as shown in the Profile. But when there is no Fullname  'display_name' stays empty. 

As I said I already fixed this. Since I started working on some other features and already pushed some commits to my branch I'm going to finish the stuff Iḿ working on first and send an pull request to this one.

About the two Icons. I changed this file on my system:

/usr/share/applications/skype.desktop

and replaced the line: 

Exec=skype

with:

Exec=skype-wrapper

**Comment by Vincent123** [comment] 2012-08-28 15:35
Both guys who I asked to write me have 'full names'.

**Comment by stonerl** [comment] 2012-08-28 15:53
Ok,

so the envelop only works when the window is minimized. Do get notifications as well in that case? What I have seen is that sometimes the first chat message doesn't get displayed. Does it work when someone writes you a message you don't read it, leave Skype closed and then he writes you a second one? Does this one get displayed?

**Comment by grissir** [comment] 2012-08-28 15:54
Hi,
please use the unstable ppa, which has an older version of 
skype-wrapper. So remove skype-wrapper and the normal ppa then add 
thisone https://launchpad.net/~skype-wrapper/+archive/unstable and 
install skype-wrapper again and tell us again whether it has worked

**Comment by grissir** [comment] 2012-08-28 15:58
Ok when two people have different ideas it could get a bit confusing ... Try Toni's idea first, if it doesn't help use the older better tested version

**Comment by Vincent123** [comment] 2012-08-28 16:18
When two people have different ideas - that's great!
I guess the trick to fix 2 icons worker, nice.
Now the problem is that I can't find people to test that.
Installed the version from the unstable ppa, waiting.
By the way, should that 'test' even button work for a new message test? For me it doesn't.
If I knew that it works, I may not need people for testing.

**Comment by grissir** [comment] 2012-08-28 16:26
sorry don't know which 'test' you mean

**Comment by grissir** [comment] 2012-08-28 16:27
you can add me my skype name is grissi123

**Comment by stonerl** [comment] 2012-08-28 16:27
One more thing. Start skype-wrapper wait for Skype to get online and load the Contact List. Then go offline and wait for Skype to clear the Contact List. Then go online again wait for the contacts to come online again. Now wait for messages. :)

**Comment by Vincent123** [comment] 2012-08-28 16:34
hey guys!
I got it working fine, when messages get delivered from the 2nd attempt!
awesome, at least this is much better :D
my skype id is nikita9532
p.s. test - I mean, in skype settings>notifications that's possible to test an event

**Comment by stonerl** [comment] 2012-08-28 16:44
Great. So its working only with unstable or the stable as well?

**Comment by Vincent123** [comment] 2012-08-28 16:53
For me it did only with unstable.
I can check one more time a bit later :)

**Comment by stonerl** [comment] 2012-08-28 16:59
Would be great. I'm going to add you later on skype.

**Comment by stonerl** [comment] 2012-08-28 18:34
Ok i tested it. It works with the stable on the second attempt, too. I added a fix for this as well in my branch.

**Comment by grissir** [comment] 2012-08-29 14:03
Have not much time right now make a pull request

**Comment by Vincent123** [comment] 2012-08-29 14:12
Don't know how you guys talk to each other and if all the discussion participants know about the progress, but since other people may find this in google...
stonerl's branch worked fine, now I get message notifications and the 'blue envelope' works too.
For me it all was like:
1) Install the version from stonerl's branch
2) https://github.com/sagetarian/skype-wrapper/issues/68#issuecomment-8095355 this tip about 'two icons'
3) Pinned the wrapper icon to the unity launcher (left panel)
4) Added 'skype-wrapper' command to the autostart applications list
And yes, configured Empathy is needed!

**Comment by grissir** [comment] 2012-08-29 20:53
Ok ppa is updated reopen the bug if it's still not working

**Closed as completed** 2012-08-29 20:52 UTC
