### ISSUE TITLE
Skype-wrapper keeps pushing old events

### ISSUE THREAD

**Issue by gvansanden** [sagetarian/skype-wrapper#59] opened 2012-05-22 08:28 UTC
Installed skypewrapper on Ubuntu precise from PPA (Version: 0ubuntu6.2.1~precise2).  Everytime it starts, it pushes old notifications (while Skype native notifications only come for new events). 

Also, two old messages stay in the message indicator and on the unity panel, they are 3000 and 4000 hours old.  I cannot dismiss them in any way.

**Comment by purple52** [comment] 2012-05-25 07:57
I have this issue too; there are two old messages (from the same group chat) that always pop up as notifications when skype-wrapper is started, and then the message indicator permanently shows that chat as having updates. If there's any debugging I can help with, please let me know.

**Comment by grissir** [comment] 2012-05-25 09:25
Me too, but it disappeared maybe you can delete all the config files

**Comment by grissir** [comment] 2012-05-29 12:32
Ok can you please try the following: Open skype, open all chats having notifications and then quit skype via the quicklist
It disappeared for me.
Thanks

**Comment by grissir** [comment] 2012-05-29 12:34
ok forget about it it only works one time

**Comment by grissir** [comment] 2012-06-01 11:05
Ok try to remove the .Skype folder in your home directory... It removes your history!! but since I done this I'm not able to reproduce the bug anymore

**Comment by purple52** [comment] 2012-06-08 09:06
Yes, moving/removing the .Skype folder clears the stuck notifications. Interestingly, replacing the original .Skype folder makes the notifications return, so I can still reproduce the problem.

If someone can tell me how to enable debug logging I can have a go at debugging this.

**Comment by grissir** [comment] 2012-06-08 20:27
You can install dconf editor under apps/skype-wrapper set debug-level to 5 and debug-log to true

**Comment by purple52** [comment] 2012-06-15 08:48
Thanks- I didn't find anything from the debug log, so was about to start digging into the code. But installing Skype 4.0 has also cleared the stuck notifications, so I can't test any further. Will update if the problem returns.

**Comment by grissir** [comment] 2012-06-15 10:19
I'm not sure, but the problem seems to be a skype issue cause I didn't find anything in our code, but I'm not sure about this but it's great that skype 4 resolves the problem

**Comment by mhrdev** [comment] 2012-06-22 14:01
I got rid of old events by:
1. opening the event
2. selecting "chat history -> forever"
3. scrolling to the top

**Comment by grissir** [comment] 2012-06-22 14:29
Ok thx for the tip, this makes sense

**Comment by grissir** [comment] 2012-07-07 09:24
I have now found the cause for the bug, old messages seems to be marked as unread until you scroll up to them. We can't do much about this, but skype 4 seems to have fixed this.

**Closed as completed by grissir** 2012-07-07 09:24 UTC
Labels: Bugs

**Comment by kav2k** [comment] 2014-12-15 09:19
This is not fixed by Skype 4, unfortunately. This seems to happen with my own messages synced from elsewhere while the client is running. The scrolling to the top tip does not clear it.

Using skype-wrapper 0ubuntu6.5.2~trusty0 and skype 4.3.0.37-0ubuntu0.12.04.1

If you could at least tell which files in the profile need to be wiped (I'm tired of restoring all preferences), it would be helpful.
