### ISSUE TITLE
[BUG]: notifications don't disappear

### ISSUE THREAD

**Issue by grissir** [sagetarian/skype-wrapper#27] opened 2011-11-20 12:21 UTC
Sometimes if I click on a message in a message menu the correct skype window opens, but the notification is still their and the letter is still blue (nothing to big, because their is a reset button) happens nearly every time when I get a message, when Skype is offline and someone sends me a message...

**Comment by sagetarian** [comment] 2012-05-15 08:42
i cannot seem to reproduce this .. can you check the current version available on the PPA?

**Comment by grissir** [comment] 2012-05-15 09:45
If already checked it, the ppa is not the latest version, but last time I tried to update it failed :(

**Comment by sagetarian** [comment] 2012-05-15 10:15
what system you running? you on Precise yet? if not i've just put on the latest dev releases in the github download section .. you can upgrade to the .deb (0.5.4.7) or you can can uninstall your version then install the version in the download section .. i'm making sure that i keep dev releases outside the PPA

**Comment by bilderbuchi** [comment] 2012-05-15 15:18
> i'm making sure that i keep dev releases outside the PPA 

would maybe make most sense to keep two repos, the existing one for stable releases, and a skype-wrapper-devel which is updated more often.

**Comment by sagetarian** [comment] 2012-05-15 15:45
perhaps a better alternative would be to create a dev "branch" instead? that would keep everything in one repo with the master branch as stable as possible

**Comment by bilderbuchi** [comment] 2012-05-15 15:48
ha, sorry, I used the wrong term. I meant "archive", as in a devel launchpad PPA, not (a second github) "repo"! you're right, a separate repo would make no sense at all. yes, a dev and a master branch would be the way to go, and feed two PPAs from those two branches.

**Comment by sagetarian** [comment] 2012-05-15 15:55
ah, good idea, i'll look into it :)

**Comment by sagetarian** [comment] 2012-05-15 15:55
> what system you running? you on Precise yet? if not i've just put on the latest dev releases in the github download section .. you can upgrade to the .deb (0.5.4.7) or you can can uninstall your version then install the version in the download section .. i'm making sure that i keep dev releases outside the PPA

how's this going? let me know :) thanks

**Comment by sagetarian** [comment] 2012-05-15 18:30
ppa:skype-wrapper/unstable

compliments of Christian Rupp

**Comment by bilderbuchi** [comment] 2012-05-15 20:38
hah, good, thanks. :-)

**Comment by sagetarian** [comment] 2012-05-15 21:29
i'm closing this issue as i cannot reproduce it .. feel free to reopen at anytime

**Closed as completed by sagetarian** 2012-05-15 21:29 UTC
Labels: Bugs
